const assert = require('node:assert/strict');
const Wizard = require('../js/planning/planning-wizard.js');
const Core = require('../js/planning/planning-container-v2.js');
const Repository = require('../js/planning/planning-repository.js');
const profile = require('../data/pedagogy/didactics/secondary/cycle-vi/mathematics/quantity.json');

const values = new Map();
const storage = { getItem: key => values.get(key) ?? null, setItem: (key, value) => values.set(key, value) };
const repository = Repository.create({ storage, validator: Core });
for (const type of ['unit', 'project', 'learning_experience']) {
    const draft = Wizard.create(type, `plan-${type.replaceAll('_', '-')}`);
    assert.equal(draft.schemaVersion, '2.0');
    assert.equal(draft.identity.planningType, type);
    assert.ok(draft.identity.title.trim());
    assert.equal(Core.validate(draft).valid, true);
    assert.equal(Core.validate(draft, { forReview: true }).valid, false);
    repository.save(Wizard.prepareSave(draft, null));
    const reopened = Repository.create({ storage, validator: Core }).get(draft.id);
    reopened.identity.title = 'Unidad editada';
    Wizard.addCurriculum(reopened, profile);
    reopened.curriculumMap[0].criteria.push({ id: 'criterion-test', description: 'Justifica sus procedimientos.' });
    Wizard.addSession(reopened);
    Wizard.addSession(reopened);
    const firstId = reopened.sequence[0].id;
    assert.deepEqual(reopened.sequence[0].criterionRefs, ['criterion-test']);
    assert.deepEqual(reopened.sequence[0].curriculumMapRefs, [reopened.curriculumMap[0].id]);
    Wizard.reorder(reopened, 0, 1);
    assert.equal(reopened.sequence[1].id, firstId);
    assert.deepEqual(reopened.sequence.map(s => s.index), [1, 2]);
    reopened.milestones.push({ id: 'milestone-test', title: 'Hito', phase: '', objective: '', partialProduct: null, sequenceItemIds: [firstId], completionCriteria: [] });
    reopened.sequence[1].milestoneId = 'milestone-test';
    Wizard.removeSession(reopened, 1);
    assert.deepEqual(reopened.milestones[0].sequenceItemIds, []);
    const revised = Wizard.prepareSave(reopened, repository.get(draft.id));
    repository.save(revised);
    assert.equal(revised.revision, 2);
    assert.equal(revised.status, 'draft');
    assert.equal(repository.get(draft.id).identity.title, 'Unidad editada');
    assert.equal(Core.validate(revised).valid, true);
    const invalid = structuredClone(revised);
    invalid.sequence[0].criterionRefs = ['unknown'];
    assert.throws(() => Wizard.prepareSave(invalid, revised), /inválida/);
    invalid.sequence[0].week = -1;
    assert.throws(() => Wizard.prepareSave(invalid, revised), /semana/);
    assert.equal(repository.get(draft.id).revision, 2);
    const unnamed = structuredClone(revised);
    unnamed.identity.title = '  ';
    assert.throws(() => Wizard.prepareSave(unnamed, revised), /título/);
}
assert.throws(() => Wizard.create('context'), /tipo/);
assert.equal(Wizard.canCreate('unit', { ok: true, features: { 'planning.unit': true } }), true);
assert.equal(Wizard.canCreate('project', { ok: true, features: { 'planning.experience': true } }), true);
assert.equal(Wizard.canCreate('unit', { ok: true, features: {} }), false);
assert.equal(Wizard.canCreate('unit', null), false);
const earlySequence = Wizard.create('unit');
Wizard.addSession(earlySequence);
Wizard.addCurriculum(earlySequence, profile);
assert.deepEqual(earlySequence.sequence[0].curriculumMapRefs, [earlySequence.curriculumMap[0].id]);
console.log('planning-wizard.test.js: OK');
